BEGIN TRY

BEGIN TRAN;

-- CreateSchema
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'dbo') EXEC sp_executesql N'CREATE SCHEMA [dbo];';

-- CreateTable
CREATE TABLE [dbo].[users] (
    [uid] NVARCHAR(128) NOT NULL,
    [email] NVARCHAR(256) NOT NULL,
    [displayName] NVARCHAR(256),
    [createdAt] DATETIME2 CONSTRAINT [DF__users__createdAt__5070F446] DEFAULT CURRENT_TIMESTAMP,
    [status] NVARCHAR(50) CONSTRAINT [DF__users__status__5165187F] DEFAULT 'active',
    CONSTRAINT [PK__users__DD7012645CE56F39] PRIMARY KEY CLUSTERED ([uid]),
    CONSTRAINT [UQ__users__AB6E61649A9D41E9] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH

